### ISSUE TITLE
iperf3 test causes a panic in linkerd-tcp

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd-tcp#47]
Here's my test setup:

iperf3 installed on on netty-test-8, proxy-test-4d, proxy-test-4e.

`proxy-test-4e` has an iperf server listening on `7474` using the command `iperf3 -s -p 7474 -d`
`proxy-test-4d` has a namerd and a linkerd-tcp.
`netty-test-8` runs an iperf client: `iperf3 -c proxy-test-4d -p 7474 -i 1 -t 120 -b 10M`

I did not find an iperf speed that did not cause a panic or a drop to 0 in traffic after the first second.

The iperf client output
```
stevej@netty-test-8:~$ iperf3 -c proxy-test-4d -p 7474 -i 1 -t 120 -b 10M
Connecting to host proxy-test-4d, port 7474
[  4] local 10.240.0.4 port 37294 connected to 10.240.0.21 port 7474
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   497 KBytes  4.07 Mbits/sec    1    188 KBytes
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    0    188 KBytes
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0    188 KBytes
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    0    188 KBytes
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0    188 KBytes
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0    188 KBytes
^C[  4]   6.00-6.55   sec  0.00 Bytes  0.00 bits/sec    0    188 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-6.55   sec   497 KBytes   622 Kbits/sec    1             sender
[  4]   0.00-6.55   sec  0.00 Bytes  0.00 bits/sec                  receiver
iperf3: interrupt - the client has terminated
```

The panic in linkerd-tcp.
```
stevej@proxy-test-4d:~/src/linkerd-tcp$ RUST_BACKTRACE=full target/release/linkerd-tcp example.yml
Listening on http://0.0.0.0:9989.
thread 'main' panicked at 'destination and source slices have different lengths', /checkout/src/libcore/slice/mod
.rs:591
stack backtrace:
   0:     0x564fcbf38e63 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x564fcbf34cf4 - std::sys_common::backtrace::_print::hcef39a9816714c4c
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x564fcbf3b7a7 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x564fcbf3b32b - std::panicking::default_hook::h0bf7bc3112fb107d
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x564fcbf3bc7b - std::panicking::rust_panic_with_hook::ha27630c950090fec
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x564fcbf3bb54 - std::panicking::begin_panic::heb97fa3158b71158
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x564fcbf3ba89 - std::panicking::begin_panic_fmt::h8144403278d84748
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x564fcbf3ba17 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x564fcbf66efd - core::panicking::panic_fmt::h3b0cca53e68f9654
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x564fcbf66e34 - core::panicking::panic::h4b991f5abe7d76d5
                               at /checkout/src/libcore/panicking.rs:49
  10:     0x564fcbdf5f7c - <linkerd_tcp::lb::proxy_stream::ProxyStream as futures::future::Future>::poll::h16aa78
271f3f436f
                               at /checkout/src/libcore/macros.rs:21
                               at /checkout/src/libcollections/slice.rs:1313
                               at /home/stevej/src/linkerd-tcp/src/lb/proxy_stream.rs:134
  11:     0x564fcbdf0a86 - <linkerd_tcp::lb::duplex::Duplex as futures::future::Future>::poll::h1c7157b5df76e8fa
                               at /home/stevej/src/linkerd-tcp/src/lb/duplex.rs:61
  12:     0x564fcbdf1ffb - linkerd_tcp::lb::endpoint::Endpoint::poll_connections::hd32a91fb1036e124
                               at /home/stevej/src/linkerd-tcp/src/lb/endpoint.rs:184
                               at /home/stevej/src/linkerd-tcp/src/lb/endpoint.rs:169
  13:     0x564fcbdb0b6d - <futures::sink::map_err::SinkMapErr<S, F> as futures::sink::Sink>::poll_complete::h8f7
93e2eb4aa3e54
                               at /home/stevej/src/linkerd-tcp/src/lb/balancer.rs:103
                               at /home/stevej/src/linkerd-tcp/src/lb/balancer.rs:392
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/sink/map_err.rs:29
  14:     0x564fcbdd5f31 - <linkerd_tcp::driver::Driver<S, K> as futures::future::Future>::poll::h2b4329b0261a742
3
                               at /home/stevej/src/linkerd-tcp/src/driver.rs:62
  15:     0x564fcbf0ace6 - tokio_core::reactor::Core::poll::hc95af26313ea35eb
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/future/mod.rs:106
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/task_impl/mod.rs:337
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/task_impl/mod.rs:484
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/task_impl/mod.rs:61
                               at /checkout/src/libstd/thread/local.rs:253
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/task_impl/mod.rs:54
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/task_impl/mod.rs:484
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src
/task_impl/mod.rs:337
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/s
rc/reactor/mod.rs:366
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/s
rc/lib.rs:135
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/s
rc/reactor/mod.rs:366
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/s
rc/reactor/mod.rs:324
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/s
rc/reactor/mod.rs:312
  16:     0x564fcbc46040 - tokio_core::reactor::Core::run::h96e50dceabf7d65e
                               at /home/stevej/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/s
rc/reactor/mod.rs:249
  17:     0x564fcbc4dc77 - linkerd_tcp::main::h58ef6ee19fe9e824
                               at /home/stevej/src/linkerd-tcp/src/app/mod.rs:107
                               at /home/stevej/src/linkerd-tcp/src/main.rs:52
  18:     0x564fcbf3b975 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libcore/ops.rs:2606
                               at /checkout/src/libstd/panicking.rs:454
  19:     0x564fcbf42c6a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
 20:     0x564fcbf3c41a - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  21:     0x7f0f6f2e53f0 - __libc_start_main
  22:     0x564fcbc45c59 - _start
  23:                0x0 - <unknown>
```

**Comment by stevej** [comment]
The panic comes from the slice primitive slice, specifically from`clone_from_slice` https://github.com/rust-lang/rust/blob/master/src/libcore/slice/mod.rs#L590

**Comment by stevej** [comment]
Some trace log lines right before the panic

```
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: poll
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.4:37388))).read(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: read 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.10:7474))).write(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: wrote 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.4:37388))).read(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: read 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.10:7474))).write(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: wrote 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.4:37388))).read(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: read 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.10:7474))).write(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: wrote 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.4:37388))).read(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: read 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.10:7474))).write(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: wrote 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.4:37388))).read(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: read 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.10:7474))).write(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: wrote 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.4:37388))).read(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: read 8192 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::socket      ^[[0m: Socket(Plain(V4(10.240.0.10:7474))).write(8192)
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: wrote 6656 bytes
^[[35mTRACE^[[0m:^[[1mlinkerd_tcp::lb::proxy_stream^[[0m: saving 1536 bytes
thread 'main' panicked at 'destination and source slices have different lengths', /checkout/src/libcore/slice/mod.rs:591
stack backtrace:
   0:     0x5623f50f2e63 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5623f50eecf4 - std::sys_common::backtrace::_print::hcef39a9816714c4c
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x5623f50f57a7 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x5623f50f532b - std::panicking::default_hook::h0bf7bc3112fb107d
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x5623f50f5c7b - std::panicking::rust_panic_with_hook::ha27630c950090fec
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x5623f50f5b54 - std::panicking::begin_panic::heb97fa3158b71158
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x5623f50f5a89 - std::panicking::begin_panic_fmt::h8144403278d84748
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x5623f50f5a17 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x5623f5120efd - core::panicking::panic_fmt::h3b0cca53e68f9654
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x5623f5120e34 - core::panicking::panic::h4b991f5abe7d76d5
                               at /checkout/src/libcore/panicking.rs:49
  10:     0x5623f4faff7c - <linkerd_tcp::lb::proxy_stream::ProxyStream as futures::future::Future>::poll::h16aa78271f3f436f```
